security:

    access_denied_url: /

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path:    /
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path:   /logout
                target: / #This is home url
            anonymous:    true

    access_control:
        - { path: ^/login, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/register, allow_if: "not has_role('ROLE_USER')" }

